from datetime import date
from typing import Any, Protocol


class StateStorePort(Protocol):
    def acquire_run_lock(self, run_key: str) -> bool: ...

    def refresh_run_lock(self, run_key: str) -> bool: ...

    def release_run_lock(self, run_key: str) -> None: ...

    def get_last_checkpoint(self, mailbox: str) -> dict[str, Any] | None: ...

    def save_checkpoint(self, mailbox: str, checkpoint: dict[str, Any]) -> None: ...

    def is_processed(self, message_id: str | None, content_hash: str) -> bool: ...

    def mark_processed(self, message_id: str | None, content_hash: str, run_id: str) -> None: ...

    def mark_processed_batch(self, records: list[tuple[str | None, str, str]]) -> None: ...

    def start_run(self, run_id: str, date_ref: date) -> None: ...

    def update_run_status(self, run_id: str, status: str, checkpoint: str) -> None: ...

    def finish_run(self, run_id: str, status: str, error: str | None = None) -> None: ...

    def get_missed_run_dates(self, days_back: int) -> list[date]: ...

    def list_runs(
        self,
        limit: int = 100,
        date_from: date | None = None,
        date_to: date | None = None,
    ) -> list[dict[str, Any]]: ...
